site_name: Flowdyn
repo_name: flowdyn
repo_url: https://github.com/jgressier/flowdyn
edit_uri: ''  #disables edit button

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  language: en
  #features:
  #  - navigation.tabs

nav:
  - Home: index.md
  - User Guide:
    - Models: userguide/models.md
    - Numerical methods: userguide/num.md
  - Examples: examples.md
  - About: about.md

plugins:
  - search