[tool.poetry]
name = "flowdyn"
version = "1.0.0"
description = "Model of discretization of hyperbolic model, base is Finite Volume method"
authors = ["j.gressier <jeremie.gressier@isae-supaero.fr>"]
license = "MIT"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Software Development :: Libraries :: Python Modules" ]
exclude = [ "examples", "lessons" 

[tool.poetry.dependencies]
python = "^3.5"
numpy = "^1.14"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--cov -v"
testpaths = [
    "tests"
]
